spring.application.name=student-management [cite: 597]
server.port=${PORT:8080} [cite: 598]

# Lay gia tri tu bien moi truong DATABASE_URL, neu khong co thi dung localhost (cho dev) [cite: 600]
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/student-management} [cite: 600]
spring.datasource.username=${DB_USERNAME:postgres} [cite: 601]
spring.datasource.password=${DB_PASSWORD:123} [cite: 602]
spring.datasource.driver-class-name=org.postgresql.Driver [cite: 603]

# JPA/Hibernate [cite: 604]
spring.jpa.hibernate.ddl-auto=update [cite: 605]
spring.jpa.show-sql=true [cite: 612]
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect [cite: 613]